version: 2.1

orbs:
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.0

workflows:
  build:
    jobs:
      # -- PR check jobs ------------------------------------------
      - kurtosis-docs-checker/check-docs:
          markdown-link-check-config-json: |
            {
                "replacementPatterns": [
                    { 
                        "pattern": "^./kurtosis-core",
                        "replacement": "https://docs.kurtosistech.com/kurtosis-core"
                    },
                    { 
                        "pattern": "^./kurtosis-engine-server",
                        "replacement": "https://docs.kurtosistech.com/kurtosis-engine-server"
                    },
                    { 
                        "pattern": "^./kurtosis-cli",
                        "replacement": "https://docs.kurtosistech.com/kurtosis-cli"
                    },
                    { 
                        "pattern": "^./kurtosis-libs", 
                        "replacement": "https://docs.kurtosistech.com/kurtosis-libs"
                    },
                    { 
                        "pattern": "^./kurtosis-client", 
                        "replacement": "https://docs.kurtosistech.com/kurtosis-client"
                    },
                    { 
                        "pattern": "^./kurtosis-testsuite-api-lib", 
                        "replacement": "https://docs.kurtosistech.com/kurtosis-testsuite-api-lib"
                    }
                ]
            }
          filters:
            branches:
              ignore:
                - develop
                - master
